id = "mcp-n8n"
name = "n8n MCP Server"
version = "0.1.0"
schema_version = 1
authors = ["Hans Doebel <hansdev@mailbox.org>"]
description = "n8n MCP Server for Zed"
repository = "https://github.com/hansdoebel/zed-mcp-n8n"

[context_servers.mcp-n8n]
